name: 📦 Build npm Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        if: (github.repository == 'KaotoIO/forms' && github.event_name == 'push') || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
        id: app-token
        with:
          app-id: ${{ vars.KAOTO_RELEASE_APP_ID }}
          private-key: ${{ secrets.KAOTO_RELEASE_APP_KEY }}

      - name: 🛎️ Checkout source code
        uses: actions/checkout@v4
        with:
          token:  ${{ steps.app-token.outputs.token || github.token }}

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: 📦 Build the library
        run: yarn build

      - name: 💅 Run eslint
        run: yarn workspaces foreach --verbose --all --topological-dev run lint
      
      - name: 📤 Upload artifacts for publish (only on main)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'KaotoIO/forms'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.KAOTO_NPM_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          yarn publish

      - name: 📦 Upload pages artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: 🚀 Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
